function write_ns3d_snapshot(iter, runDir, coord, para, state)
OUTPUT_Tecplot3d(iter, runDir, gather_ns3d_value(coord), ...
    para.nx_all, para.ny_all, para.nz_all, 'U,V,W,PRE', ...
    gather_ns3d_value(state.uNew(:)), gather_ns3d_value(state.vNew(:)), ...
    gather_ns3d_value(state.wNew(:)), gather_ns3d_value(state.p(:)));
end
